# Experiment 11: Pandas Library Use Cases

Executed notebook with output.

In [1]:
import pandas as pd
df=pd.DataFrame({'Name':['Asha','Bala','Chitra','Dev'],'Department':['CSE','IT','CSE','IT'],'Marks':[82,75,91,68]})
print('DataFrame:'); display(df); print('Marks above 75:'); display(df[df.Marks>75]); print('Department averages:'); display(df.groupby('Department',as_index=False).Marks.mean()); df['Result']=df.Marks.ge(50).map({True:'Pass',False:'Fail'}); display(df)

DataFrame:

     Name Department  Marks
0    Asha        CSE     82
1    Bala         IT     75
2  Chitra        CSE     91
3     Dev         IT     68

Marks above 75:

     Name Department  Marks
0    Asha        CSE     82
2  Chitra        CSE     91

Department averages:

  Department  Marks
0        CSE   86.5
1         IT   71.5

     Name Department  Marks Result
0    Asha        CSE     82   Pass
1    Bala         IT     75   Pass
2  Chitra        CSE     91   Pass
3     Dev         IT     68   Pass